version: '3.3'
services:
    mysqldb:
        build: ./backend/A708_backend_db/MYSQL
        env_file:
            - ./backend/A708_backend_db/mysql.env
        container_name: db_mysql
        ports:
            - '3306:3306'
        volumes:
            - ./backend/A708_backend_db/MYSQL/res/data/:/var/lib/mysql

    backend_spring:
        build: ./backend/A708_backend_springboot
        container_name: backend_spring
        ports:
            - '8080:8080'
        volumes:
            - ./backend/A708_backend_springboot:/srv/docker-server
    
    sio_server:
        build: ./backend/A708_backend_proxyserver
        container_name: backend_sio
        ports:
            - '8081:8081'
    # nginx:
    #     image: nginx:1.15-alpine
    #     container_name: nginx
    #     restart: unless-stopped
    #     volumes:
    #         - ./nginx:/et/nginx/conf.d 
    #       #  - ./data/certbot/conf:/etc/letsencrypt
    #       #  - ./data/certbot/www:/var/www/certbot
    #     ports:
    #         - '80:80'
    #         - '443:443'
    #     command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; don & nginx -g \"daemon off;\"'"
